### ISSUE TITLE
Readme for first time users

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-container-toolkit#46]
## Please describe what you would like to see in this project

I would like to see the current README replaced with a guide for first-time users of Carpenter to publish their own plugin.

## Please describe your use case

Plugins in other organizations and/or CI systems.

**Comment by jdowni000** [comment]
I have began to create a new README.md that is more friendly to users [here](https://github.com/jdowni000/arcaflow-plugin-image-builder/blob/docs/README_UPDATE.md#using-carpenter-in-reusable-workflow). This is a WIP. Additionally, the link will break when the naming convention is changed to simply README.md.
