### ISSUE TITLE
Integrate arcaflow-docsgen

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcaflow-container-toolkit#47]
## Please describe what you would like to see in this project

As an optional feature, Carpenter should probably integrate [Arcaflow-DocsGen](https://github.com/arcalot/arcaflow-docsgen) to keep a README.md or similar updated. The feature should be optional and the markdown file should be configurable.

## Please describe your use case

Keep the documentation for plugins updated.

## Additional context

Arcaflow-DocsGen is early in development and should be considered carefully.

**Comment by jdowni000** [comment]
I have a working prototype [here](https://github.com/jdowni000/arcaflow-docsgen/blob/dev/.github/workflows/reusable_workflow.yaml). I am using this as a reusable workflow we can add to your current CI workflow for plugins that use ACT. Documentation is still to come

**Comment by jdowni000** [comment]
I have merged the PR. I will begin implementing this into all official plugin repository workflows. Once done, I will close the issue.

**Comment by jdowni000** [comment]
I have PR's out for the official plugins with a few exceptions of buildtime errors that will need to be addressed in separate PR's. The foundation for implementation is complete and can be introduced to the repositories moving forward.
